M48
; DRILL file {KiCad (7.0.0)} date Fri Apr 21 00:04:55 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-21T00:04:55-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X169.725Y-64.802
X169.725Y-89.312
X216.675Y-64.802
X216.675Y-89.312
T0
M30
